### ISSUE TITLE
Post Migration - Split UT and IT in separate jobs

### ISSUE THREAD

**Issue by javiertuya** [giis-uniovi/modevo#21]
Review things that were left pending in #7:
- Each module includes either unit or integration tests: split in separate jobs, each will run all tests of a module.
- Job names are test-*, where * can be ut, it or the name of the module
- Each job must generate an artifact with all its reports
- The beginning of the sonarqube job must consolidate all artifacts and generate a final artifact with the consolidated test report
- Note that coverage reports must be sent to sonarqube

You can see an example in other repositories, eg. tdrules. Note that the tdrules reporting is a little bit more complicated (but this is not needed here) as we do not need a separate job for test reports becasue we are not going to publish en GH actions.

**Comment by giis-qabot** [comment]
@suarezgpablo This is a **reminder** about this issue because it has not been updated for **10 days**

**Comment by javiertuya** [comment]
I've checked the Sonar main branch and it seems that it is only getting coverage from one of the modules:

https://sonarcloud.io/component_measures?metric=coverage&id=my%3Amodevo

**Comment by suarezgpablo** [comment]
> I've checked the Sonar main branch and it seems that it is only getting coverage from one of the modules:
> 
> https://sonarcloud.io/component_measures?metric=coverage&id=my%3Amodevo

@javiertuya I was able to fix another mistake that I had where test-report-ALL was empty but I'm stuck on this issue. 

I tested it with several options but I always ended up with the coverage of only one module, the last one of the restore-artifact-name# list. For instance, right now it is only getting coverage from the script module, which is given to sonarqube through "restore-artifact-name2". If I remove "restore-artifact-name2" then it analyzes the transform module, which is give to sonarqube through "restore-artifact-name1". In summary, it ignores all but the last of test-report-files. 

I checked with giis-uniovi/tdrules and I think that I'm doing the same as there. I also checked the documentation of javiertuya/sonarqube-action and I think that I'm not missing any required parameters. Could you take a quick look to see if I'm maybe  overlooking something?

      ```
- uses: javiertuya/sonarqube-action@v1.3.1
        with: 
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          restore-artifact-name1: "test-report-files-transform"
          restore-artifact-name2: "test-report-files-script"
```
